package com.softdesign.sosapplication.utils.common;

public interface ConstantManager {
    int REQUEST_CODE_ACCESS_FINE_LOCATION = 111;
    int REQUEST_CODE_WORK_CONTACTS = 222;
    int REQUEST_CODE_SEND_SMS = 333;
    int DIALOG_EXIT = 1;
    int DIALOG_SOS_EXIT = 2;
    int DIALOG_PATH_DEFAULT_USER = 346;
    int DIALOG_PATH_START = 34236;
    int DIALOG_PATH_SOS = 2343;
    String CONDITION_USER_FROM_DIALOG = "CONDITION_USER_FROM_DIALOG_TRUE";
    String SAVE_CONTACT_CONSTANT = "TELETHON:";
    String SIZE_CONTACT_CONSTANT = "SIZE_CONTACTS";
    String SAVE_SHOW_CONTACT_DIALOG = "SHOW_CONTACT_DIALOG";
    String SAVE_COORDINAT_ONE = "SAVE_COORDINAT_ONE";
    String SAVE_COORDINAT_TWO = "SAVE_COORDINAT_TWO";
    String SAVE_SIZE_COORDINATS = "SAVE_SIZE_COORDINATS";
    String SAVE_IS_ROAD = "SAVE_IS_ROAD";
    int PERMISSION_GPS = 444;

    int CHECK_SETTINGS_CODE = 5;
    int REQUEST_LOCATION_PERMISSION = 546;
}
