package com.softdesign.sosapplication.utils.common;

public interface ConstantManager {
    int REQUEST_CODE_ACCESS_FINE_LOCATION = 111;
    int REQUEST_CODE_WORK_CONTACTS = 222;
    int REQUEST_CODE_SEND_SMS = 333;
    int DIALOG_EXIT =1;
    int DIALOG_SOS_EXIT =2;
    String CONDITION_USER_FROM_DIALOG = "CONDITION_USER_FROM_DIALOG_TRUE";
    String SAVE_CONTACT_CONSTANT = "TELETHON:";
    String SIZE_CONTACT_CONSTANT = "SIZE_CONTACTS";
    String SAVE_SHOW_CONTACT_DIALOG = "SHOW_CONTACT_DIALOG";
    int PERMISSION_GPS = 444;

}
